module.exports = {
	apps: [
		{
			name: "frontend",
			cwd: "/app/apps/frontend",
			script: "pnpm",
			args: "start",
			env: {
				NODE_ENV: "production",
				PORT: process.env.FRONTEND_PORT,
				NEXT_PUBLIC_CP_PORT: process.env.CONTROL_PLANE_PORT,
				OPENROUTER_API_KEY: process.env.OPENROUTER_API_KEY,
				OPENROUTER_MODEL: process.env.OPENROUTER_MODEL,
			},
			error_file: "/dev/stderr",
			out_file: "/dev/stdout",
			time: true,
		},
		{
			name: "control-plane",
			cwd: "/app/apps/control-plane",
			script: "pnpm",
			args: "start",
			env: {
				NODE_ENV: "production",
				PORT: process.env.CONTROL_PLANE_PORT,
				DATABASE_PATH: process.env.DATABASE_PATH,
				OPENROUTER_API_KEY: process.env.OPENROUTER_API_KEY,
				OPENROUTER_MODEL: process.env.OPENROUTER_MODEL,
				AGENT_PORT: process.env.AGENT_PORT,
				CONTROL_PLANE_PORT: process.env.CONTROL_PLANE_PORT,
			},
			error_file: "/dev/stderr",
			out_file: "/dev/stdout",
			time: true,
		},
		{
			name: "agent",
			cwd: "/app/apps/agent",
			script: "pnpm",
			args: "start",
			env: {
				NODE_ENV: "production",
				PORT: process.env.AGENT_PORT,
			},
			error_file: "/dev/stderr",
			out_file: "/dev/stdout",
			time: true,
		},
	],
}
